# Generated by Django 5.0.7 on 2024-07-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_sku', models.CharField(max_length=50, unique=True)),
                ('product_price', models.FloatField()),
                ('product_quantity', models.IntegerField()),
                ('product_supplier', models.CharField(max_length=100)),
            ],
        ),
    ]
