# Generated by Django 5.0.7 on 2024-07-27 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_sku',
            new_name='sku',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_supplier',
            new_name='supplier',
        ),
    ]
